[tool.black]
line-length = 100
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
(
  ^/airflow/logs
| ^/data
| ^/models
| ^/evaluation
| ^/prometheus
| ^/grafana
| ^/.dvc
| ^/.git
| ^/.venv
| ^/venv
| ^/__pycache__
)
'''
