channels:
- conda-forge
dependencies:
- python=3.12.11
- pip<=25.0.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.1.1
  - numpy==2.3.2
  - pandas==2.3.1
  - pyarrow==17.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
  - xgboost==3.0.3
name: mlflow-env
