FROM apache/airflow:2.8.1-python3.10
USER root
# Copie le fichier dans un répertoire accessible
COPY airflow/requirements.txt /requirements.txt

# Change temporairement les droits pour l'utilisateur airflow
RUN chown airflow: /requirements.txt

# Revenir à l'utilisateur airflow pour l'installation
USER airflow

# Installer les dépendances dans le bon environnement
RUN pip install --no-cache-dir -r /requirements.txt
