name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Uninstall system pyarrow (avoid ABI mismatch)
        run: |
          pip uninstall -y pyarrow || true

      - name: Install base deps for tests
        run: |
          pip install "numpy<2" "pandas==2.2.3"
          pip install pytest ruff black pyyaml
          pip install python-box==7.2.0
          pip install prometheus-client==0.20.0
          pip install joblib==1.4.2

      - name: Install extra deps for config
        run: pip install python-box==7.2.0

      # Lint
      - name: Ruff
        run: ruff check . --fix

      - name: Black (check only)
        run: black --check .

      - name: Set PYTHONPATH for tests
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Pytest
        run: pytest -q
